#!/bin/bash

#$ -N scite-dvh03_5
#$ -o /proj/omics4tb/sturkarslan/scite_single_cells_syntrophy/scitelog-dvh-03_5cells.txt
#$ -e /proj/omics4tb/sturkarslan/scite_single_cells_syntrophy/scitelog-dvh-03_5cells.txt
#$ -P Bal_sturkars
#$ -pe serial 16
#$ -q baliga
#$ -S /bin/bash
#$ -m abe
#$ -M sturkarslan@systemsbiology.org

cd /users/sturkars/github/SCITE/

./scite -i /proj/omics4tb/sturkarslan/scite_single_cells_syntrophy/dvh-UA3-152-03_noan_mutation_counts_verified_5cells_mutation_matrix.txt -names /proj/omics4tb/sturkarslan/scite_single_cells_syntrophy/dvh-UA3-152-03_noan_mutation_counts_verified_5cells_mutation_names.txt -n 56 -m 94 -r 1 -l 900000 -fd 6.04e-5 -ad 0.21545 0.21545 -a -e 0.7
